// Generated by Wrangler on Fri Jun 28 2024 18:40:45 GMT+0100 (British Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	AUTH_TOKEN: "";
	RESTATE_INGRESS: "http://localhost:8080";
}
